### ISSUE TITLE
Authentication failed with customized username and password

### ISSUE THREAD

**Issue by heanlan** [grafana/clickhouse-datasource#106]
**Describe the bug**
I added customized username and password for ClickHouse: 
```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  labels:
    app: clickhouse
  name: clickhouse
spec:
  configuration:
    clusters:
    - layout:
        replicasCount: 1
        shardsCount: 1
      name: clickhouse
    users:
      clickhouse_customized/password: clickhouse_password
  defaults:
    templates:
      podTemplate: pod-template
  templates:
    podTemplates:
    - name: pod-template
      spec:
        containers:
        - image: yandex/clickhouse-server:21.11
          name: clickhouse
```
And verified we're able to access the database with the username&password by running: 
```shell
kubectl exec -it chi-clickhouse-clickhouse-0-0-0 -- clickhouse-client -u clickhouse_customized --password clickhouse_password
ClickHouse client version 21.11.11.1 (official build).
Connecting to localhost:9000 as user clickhouse_customized.
Connected to ClickHouse server version 21.11.11 revision 54450.
```
Grafana datsource provider yaml:
```yaml
apiVersion: v1
data:
  datasource_provider.yml: |
    apiVersion: 1
    datasources:
      - name: ClickHouse
        type: grafana-clickhouse-datasource
        access: proxy
        url: http://<svc>:8123
        editable: true
        jsonData:
          server: <svc>
          port: 9000
          username: clickhouse_customized
        secureJsonData:
          password: clickhouse_password
kind: ConfigMap
metadata:
  name: grafana-datasource-provider-h868k56k95
```
Got the following error at Grafana datasource save&test: 
```
code: 516, message: clickhouse_customized: Authentication failed: password is incorrect or there is no user with such name
```

**Versions**
Grafana and Plugin versions.
v8.3.3
v1.0.1

**Expected behavior**
Login successfully. 

**Screenshots**
![Screen Shot 2022-03-03 at 4 03 37 PM](https://user-images.githubusercontent.com/80798942/156652715-d1959adb-398b-4d4c-bc48-a02340880cae.png)

**Additional context**
The default username/password:clickhouse_operator/clickhouse_operator_password works well. 
![image](https://user-images.githubusercontent.com/80798942/156652345-3b2521fc-d9ea-4600-9292-5773eb651e8d.png)
