### ISSUE TITLE
Any variable on dashboard breaks 'SELECT 1 UNION ALL SELECT 2;'

### ISSUE THREAD

**Issue by IgorOhrimenko** [grafana/clickhouse-datasource#132]
**Describe the bug**

**Versions**
Grafana 8.5.5
Plugin 1.1.2

**Query**
`SELECT 1 UNION ALL SELECT 2;`

**To Reproduce**
1.

<details>
  <summary>compose.yaml</summary>

```yaml
services:
  clickhouse:
    image: yandex/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
  grafana:
    image: grafana/grafana-oss:8.5.5
    ports:
      - "3000:3000"
    volumes:
      - grafana_volume:/var/lib/grafana
volumes:
  grafana_volume:
```
</details>

1.1. `docker compose up --detach`
1.2. `docker compose exec grafana grafana-cli plugins install grafana-clickhouse-datasource`

2. add datasource clickhouse

![изображение](https://user-images.githubusercontent.com/24807060/172444298-5135c620-7a2d-464d-8cc9-4ce37ab34dbe.png)

3. open explore 
http://localhost:3000/explore?left=%7B%22datasource%22:%22ClickHouse%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22queryType%22:%22sql%22,%22rawSql%22:%22SELECT%201%20UNION%20ALL%20SELECT%202;%5Cr%5Cn%22,%22meta%22:%7B%22builderOptions%22:%7B%22mode%22:%22list%22,%22fields%22:%5B%5D,%22limit%22:100%7D%7D,%22format%22:1%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D&orgId=1
and check that `SELECT 1 UNION ALL SELECT 2;` it is works

4. Greate new dashboard http://localhost:3000/dashboard/new?orgId=1 
4.1. Add a new panel
4.2. switch into SQL Editor
4.3. paste `SELECT 1 UNION ALL SELECT 2;`
4.4. Run Query
4.5. POST 200 OK with `rawSql: SELECT 1 UNION ALL SELECT 2;\r\n`

![изображение](https://user-images.githubusercontent.com/24807060/172447674-6ac41980-ec0c-42ba-bb4e-2ca604f0755f.png)

5. add any variable
5.1. http://localhost:3000/dashboard/new?orgId=1&editview=templating
5.2. add var with the name query0

![изображение](https://user-images.githubusercontent.com/24807060/172445692-2a831572-4a8f-4abd-b535-eb136bea52e8.png)

5.3. go back to panel and Run Query
5.4. POST 400 Bad Request with `rawSql: SELECT 2 UNION ALL`

![изображение](https://user-images.githubusercontent.com/24807060/172447181-e7dc71e4-b1fa-4988-a84c-3e67af8727a9.png)

**Expected behavior**
POST 200 OK with correct SQL
