### ISSUE TITLE
`Port` should allow string and parse it as `int64` in Go

### ISSUE THREAD

**Issue by marcustut** [grafana/clickhouse-datasource#241]
**Describe the bug**
I am using environment variables in my `datasources.yaml` file like the following:

```yaml
apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: ${CLICKHOUSE_DATABASE}
      access: proxy
      port: ${CLICKHOUSE_PORT}
      server: ${CLICKHOUSE_HOST}
      username: ${CLICKHOUSE_USER}
      tlsSkipVerify: false
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
    isDefault: true
```

and the problem I encountered here `2022-11-22 02:32:35 logger=provisioning t=2022-11-21T18:32:35.913525135Z level=error msg="Failed to provision data sources" error="Datasource provisioning error: yaml: cannot decode !!str 
'${CLICKHOUSE_PORT}' as a !!int"`

The reason being when environment variables are injected, they're by default string. However, the Go code expects it to be an integer. 

https://github.com/grafana/clickhouse-datasource/blob/615978e7dce78e16a5a25da422be484950c1e1c4/pkg/plugin/settings.go#L14

A quick fix here would be changing 

```go
Port               int64  `json:"port,omitempty"`
``` 
to 
```go
Port               int64  `json:"port,string,omitempty"`
```

**Versions**
Grafana - v8.3.0-beta2
Plugin - v2.0.3

**To Reproduce**
1. Configure `datasources.yaml` with a string number in port.
2. Start grafana
3. See error

**Expected behavior**
Expected it to run as usual which it automatically converts to integer under the hood.
