### ISSUE TITLE
Secure Connection not activated by code

### ISSUE THREAD

**Issue by patsevanton** [grafana/clickhouse-datasource#434]
**What happened**:
Secure Connection not activated by code
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Code:
```
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: audit-clickhouse-xxx
            type: grafana-clickhouse-datasource
            jsonData:
              port: 9440
              server: 10.1.2.3
              username: user
              encrypt: true
              tlsSkipVerify: true
            secureJsonData:
              password: xxxx
```

**Screenshots**
![image](https://github.com/grafana/clickhouse-datasource/assets/10828883/30d0cbb1-ad28-4512-a2b3-96c61f87632e)

**Anything else we need to know?**:

**Environment**:

- Grafana version: 9.5.3
- Plugin version: latest
- OS Grafana is installed on: kube-prometheus-stack
- User OS & Browser: Chrome
- Others:
