### ISSUE TITLE
Unable to add Protocol and SecureConnection Toggle in datasource

### ISSUE THREAD

**Issue by naveenpg11** [grafana/clickhouse-datasource#529]
Could you please help how to add protocol and secureConnection Toogle in your example datasource ? 
I'd like to set protocol as HTTP and enable SecureConnection Toggle.
```
apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: database
      port: 9000
      server: localhost
      username: username
      tlsSkipVerify: false
    secureJsonData:
      password: password
```

**Comment by SpencerTorres** [comment]
Try adding these to the `jsonData` field:

```yaml
jsonData:
  # . . . other options . . .
  protocol: http
  secure: true
```
