### ISSUE TITLE
Plugin health check failed on create datasource

### ISSUE THREAD

**Issue by silentsokolov** [grafana/clickhouse-datasource#676]
**What happened**:
We cannot create datasource, after click "Save & Test" get error "Plugin health check failed"

**What you expected to happen**:
Datasource created

**How to reproduce it (as minimally and precisely as possible)**:

Grafana helm values:
```yaml
plugins:
  - grafana-clickhouse-datasource
  # - https://grafana.com/api/plugins/grafana-clickhouse-datasource/versions/4.0.0-beta/download;grafana-clickhouse-datasource

grafana.ini:
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  log:
    mode: console
  dataproxy:
    timeout: 6000
    keep_alive_seconds: 300
```

Connect creds:
```
github.demo.trial.altinity.cloud:8443
demo:demo
```
We also used our creds ... the same error

**Screenshots**
<img width="100" alt="image" src="https://github.com/grafana/clickhouse-datasource/assets/398939/d4ac0b32-2c31-4908-a9f6-f116626aa99f">
<img width="100" alt="image" src="https://github.com/grafana/clickhouse-datasource/assets/398939/179192bb-0b2c-4210-8f6b-da2c9bd212be">

**Environment**:

- Grafana version: Grafana v10.3.1 (00a22ff8b2)
- Plugin version: stable & 4.0.0-beta
- OS Grafana is installed on: -
- User OS & Browser: firefox / chrome
